---
# tasks file for development

- name: Install homebrew formulae
  homebrew:
    name: "{{ item.name }}"
    state: present
  loop:
    - {name: git}
  loop_control:
    label: "{{ item.name }}"

- name: Install homebrew casks
  homebrew_cask:
    name: "{{ item.name }}"
    state: present
    update_homebrew: "{{ item.update_homebrew | default('no') }}"
  loop:
    - {name: git-credential-manager, update_homebrew: yes}
    - {name: visual-studio-code}
    - {name: dotnet}
  loop_control:
    label: "{{ item.name }}"